name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.15.15"
          spago: "unstable"

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - name: Build source
        run: spago --package school-of-music build

      - name: Run tests
        run: spago test --pure